### ISSUE TITLE
Post Hatası var

### ISSUE THREAD

**Issue by berkaybeyaz1** [ismailcaakir/youtubeSearch#1]
Merhabalar class'ın 156. satırında post işleminde hatası var "/" koymuyor onu düzelletim denedim ve test ettim çalışıyor
Düzelettiğim Fonksiyon
-------------------------
	public function post($url,$q = false,$v = 2)
	{
		if ($url) {
			$this->url = $url;
		}
		if ($q){
			$this->url .= "/".$this->getEditQuery($q);
		}
		if($v){
			$this->v = "?v=".$v;

			$this->url .= $this->v;
		}
		

		$this->url .= "&alt=jsonc";
		
		$json = file_get_contents($this->url);

		$json = json_decode($json);

		return $json;
	}

-------------------------------------
düzeltilmiş hali budur iyi günler bu arada sizde inegölde yaşıyormuşsunuz galiba takip ediyorum iyi günler.

**Comment by ismailcaakir** [comment]
Teşekkürler Berkay güncelledim :)
